### ISSUE TITLE
ImportError: No module named theano

### ISSUE THREAD

**Issue by kaharjan** [mila-udem/summerschool2015#39]
I followed every steps of instructions in mac.  but when I run ipython I get following error:

> ImportError: No module named theano

I have uninstalled and reinstalled theano several times but it did not help. In python environment  I could able to import theano but not in ipython notebook. Any idea what is wrong? thank you

**Comment by nouiz** [comment]
your ipython installation probably don't use the same installation then
your python one.

You can probably fix this by adding Theano in the PYTHONPATH env variable.
Or install Theano with the same pip executable as the one corresponding to
your ipython installation stack.

**Comment by kaharjan** [comment]
thank you!!!
I finally did it through in a little complex way, in anaconda, I created new env and in this new env I installed theano, ipython, notebook then it worked...
